apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: bookshelf
    namespace: flux-system
spec:
    force: true
    interval: 1m
    path: components/bookshelf
    prune: true
    sourceRef:
        kind: OCIRepository
        name: default
    targetNamespace: default
